package com.enjoycodingfun.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.con_id
     *
     * @mbggenerated
     */
    private Long conId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_id
     *
     * @mbggenerated
     */
    private Long comId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.by_id
     *
     * @mbggenerated
     */
    private Long byId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comm_time
     *
     * @mbggenerated
     */
    private Date commTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.children
     *
     * @mbggenerated
     */
    private String children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.upvote
     *
     * @mbggenerated
     */
    private Integer upvote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.com_content
     *
     * @mbggenerated
     */
    private String comContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.con_id
     *
     * @return the value of comment.con_id
     *
     * @mbggenerated
     */
    public Long getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.con_id
     *
     * @param conId the value for comment.con_id
     *
     * @mbggenerated
     */
    public void setConId(Long conId) {
        this.conId = conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_id
     *
     * @return the value of comment.com_id
     *
     * @mbggenerated
     */
    public Long getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_id
     *
     * @param comId the value for comment.com_id
     *
     * @mbggenerated
     */
    public void setComId(Long comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.by_id
     *
     * @return the value of comment.by_id
     *
     * @mbggenerated
     */
    public Long getById() {
        return byId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.by_id
     *
     * @param byId the value for comment.by_id
     *
     * @mbggenerated
     */
    public void setById(Long byId) {
        this.byId = byId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comm_time
     *
     * @return the value of comment.comm_time
     *
     * @mbggenerated
     */
    public Date getCommTime() {
        return commTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comm_time
     *
     * @param commTime the value for comment.comm_time
     *
     * @mbggenerated
     */
    public void setCommTime(Date commTime) {
        this.commTime = commTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.children
     *
     * @return the value of comment.children
     *
     * @mbggenerated
     */
    public String getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.children
     *
     * @param children the value for comment.children
     *
     * @mbggenerated
     */
    public void setChildren(String children) {
        this.children = children == null ? null : children.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.upvote
     *
     * @return the value of comment.upvote
     *
     * @mbggenerated
     */
    public Integer getUpvote() {
        return upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.upvote
     *
     * @param upvote the value for comment.upvote
     *
     * @mbggenerated
     */
    public void setUpvote(Integer upvote) {
        this.upvote = upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.com_content
     *
     * @return the value of comment.com_content
     *
     * @mbggenerated
     */
    public String getComContent() {
        return comContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.com_content
     *
     * @param comContent the value for comment.com_content
     *
     * @mbggenerated
     */
    public void setComContent(String comContent) {
        this.comContent = comContent == null ? null : comContent.trim();
    }
}