package com.enjoycodingfun.pojo;

import java.util.Date;

public class UserContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.u_id
     *
     * @mbggenerated
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.personal
     *
     * @mbggenerated
     */
    private String personal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.rpt_time
     *
     * @mbggenerated
     */
    private Date rptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.upvote
     *
     * @mbggenerated
     */
    private Integer upvote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.downvote
     *
     * @mbggenerated
     */
    private Integer downvote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.comment_num
     *
     * @mbggenerated
     */
    private Integer commentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_content.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.id
     *
     * @return the value of user_content.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.id
     *
     * @param id the value for user_content.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.u_id
     *
     * @return the value of user_content.u_id
     *
     * @mbggenerated
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.u_id
     *
     * @param uId the value for user_content.u_id
     *
     * @mbggenerated
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.title
     *
     * @return the value of user_content.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.title
     *
     * @param title the value for user_content.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.category
     *
     * @return the value of user_content.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.category
     *
     * @param category the value for user_content.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.personal
     *
     * @return the value of user_content.personal
     *
     * @mbggenerated
     */
    public String getPersonal() {
        return personal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.personal
     *
     * @param personal the value for user_content.personal
     *
     * @mbggenerated
     */
    public void setPersonal(String personal) {
        this.personal = personal == null ? null : personal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.rpt_time
     *
     * @return the value of user_content.rpt_time
     *
     * @mbggenerated
     */
    public Date getRptTime() {
        return rptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.rpt_time
     *
     * @param rptTime the value for user_content.rpt_time
     *
     * @mbggenerated
     */
    public void setRptTime(Date rptTime) {
        this.rptTime = rptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.img_url
     *
     * @return the value of user_content.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.img_url
     *
     * @param imgUrl the value for user_content.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.nick_name
     *
     * @return the value of user_content.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.nick_name
     *
     * @param nickName the value for user_content.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.upvote
     *
     * @return the value of user_content.upvote
     *
     * @mbggenerated
     */
    public Integer getUpvote() {
        return upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.upvote
     *
     * @param upvote the value for user_content.upvote
     *
     * @mbggenerated
     */
    public void setUpvote(Integer upvote) {
        this.upvote = upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.downvote
     *
     * @return the value of user_content.downvote
     *
     * @mbggenerated
     */
    public Integer getDownvote() {
        return downvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.downvote
     *
     * @param downvote the value for user_content.downvote
     *
     * @mbggenerated
     */
    public void setDownvote(Integer downvote) {
        this.downvote = downvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.comment_num
     *
     * @return the value of user_content.comment_num
     *
     * @mbggenerated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.comment_num
     *
     * @param commentNum the value for user_content.comment_num
     *
     * @mbggenerated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_content.content
     *
     * @return the value of user_content.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_content.content
     *
     * @param content the value for user_content.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}