package com.enjoycodingfun.dao;

import com.enjoycodingfun.pojo.Upvote;

public interface UpvoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    int insert(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    int insertSelective(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    Upvote selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upvote
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Upvote record);
}